export const banks = [
    { name: "BIDV", interestRate: 5.5 },
    { name: "Vietinbank", interestRate: 5.6 },
    { name: "Vietcombank", interestRate: 5.7 },
    { name: "Agribank", interestRate: 6.5 },
    { name: "Woori Bank", interestRate: 5.2 },
    { name: "Shinhan Bank", interestRate: 7.0 },
    { name: "BVBank", interestRate: 6.49 },
    { name: "Hong Leong Bank", interestRate: 6.0 },
    { name: "SHB", interestRate: 8.19 },
    { name: "VIB", interestRate: 6.9 },
    { name: "VPBank", interestRate: 9.2 },
    { name: "Standard Chartered", interestRate: 5.8 },
    { name: "UOB", interestRate: 5.89 },
    { name: "GPBank", interestRate: 5.7 },
    { name: "Sacombank", interestRate: 7.0 },
    { name: "MSB", interestRate: 6.5 },
    { name: "SeABank", interestRate: 6.5 },
    { name: "HDBank", interestRate: 6.5 },
    { name: "TPBank", interestRate: 6.8 },
    { name: "PVcomBank", interestRate: 6.2 },
    { name: "ABBank", interestRate: 7.3 },
    { name: "MBBank", interestRate: 7.9 },
    { name: "SCB", interestRate: 7.9 },
    { name: "ACB", interestRate: 9.5 },
    { name: "OCB", interestRate: 8.49 },
    { name: "Eximbank", interestRate: 6.0 },
    { name: "HSBC", interestRate: 9.75 },
    { name: "Techcombank", interestRate: 6.3 }
  ];